[workspace]
resolver = "2"
members = [
    "live-object-sdk",
]
exclude = ["examples/"]

[workspace.package]
authors = ["Jihoon Song <jihoonsong.dev@gmail.com>"]
version = "0.1.0"
edition = "2021"
rust-version = "1.77.2"
license = "GPLv3"
